FROM python:3.11-slim

# Install ffmpeg and system libs
RUN apt-get update && apt-get install -y \
    ffmpeg \
    gcc \
    libgl1 \
    libglib2.0-0

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose port
EXPOSE 10000

# Start FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]